language: go

go:
  - 1.6.2
  - tip

script:
  - test() { go test "${1}" -coverprofile=o.txt -covermode=atomic -race && (if [ -e o.txt ]; then cat o.txt >> coverage.txt; rm o.txt; fi; true)}
  - test github.com/joushou/qp

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)